### ISSUE TITLE
docker build for libprce3 fails

### ISSUE THREAD

**Issue by mwlik** [Nautilus-Institute/quals-2024#2]
after specifying the correct `makevp.bat` file, now i get this error:
![image](https://github.com/Nautilus-Institute/quals-2024/assets/73129654/730f3ce7-bd92-46da-b238-1de6d1df0483)
from these lines:
![image](https://github.com/Nautilus-Institute/quals-2024/assets/73129654/4bca4689-f545-438c-bb9f-1882dfea334f)
any help?

**Comment by itszn** [comment]
Those files were moved to src for the release see recent dockerfile changes here: https://github.com/Nautilus-Institute/quals-2024/commit/43078bb28aad704c78a361ce92910f1bda8acb36
